/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react')['Activity']
  const BrowserRouter: typeof import('react-router')['BrowserRouter']
  const Button: typeof import('tdesign-mobile-react')['Button']
  const Navigate: typeof import('react-router')['Navigate']
  const StrictMode: typeof import('react')['StrictMode']
  const Suspense: typeof import('react')['Suspense']
  const buildTree: typeof import('../../../packages/shared/dist/main.js')['buildTree']
  const camelCase: typeof import('es-toolkit')['camelCase']
  const createContext: typeof import('react')['createContext']
  const createElement: typeof import('react')['createElement']
  const flattenTree: typeof import('../../../packages/shared/dist/main.js')['flattenTree']
  const formatDate: typeof import('../src/global/utils/time')['formatDate']
  const getChildrenNodes: typeof import('../../../packages/shared/dist/main.js')['getChildrenNodes']
  const getParentNodes: typeof import('../../../packages/shared/dist/main.js')['getParentNodes']
  const isEmpty: typeof import('../../../packages/shared/dist/main.js')['isEmpty']
  const isNil: typeof import('es-toolkit')['isNil']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const uniq: typeof import('es-toolkit')['uniq']
  const uniqBy: typeof import('es-toolkit')['uniqBy']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useEffect: typeof import('react')['useEffect']
  const useGetState: typeof import('ahooks')['useGetState']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useLocation: typeof import('react-router')['useLocation']
  const useMemo: typeof import('react')['useMemo']
  const useNavigate: typeof import('react-router')['useNavigate']
  const useOutlet: typeof import('react-router')['useOutlet']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useRoutes: typeof import('react-router')['useRoutes']
  const useSize: typeof import('ahooks')['useSize']
  const useState: typeof import('react')['useState']
  const useTranslation: typeof import('react-i18next')['useTranslation']
}
