// This file is auto-generated by @hey-api/openapi-ts

import type { PostAdminCategoryEnabledTreeResponse, PostAdminCategoryTreeResponse, PostAdminResourceRoleGrantResourceTreeResponse, PostAdminResourceRoleResourceTreeResponse, PostAdminResourceTreeResponse, PostAdminResourceUserResourceTreeResponse, PostAdminUserSignInResponse } from './types.gen';

export const postAdminResourceTreeResponseTransformer = async (data: any): Promise<PostAdminResourceTreeResponse> => {
    data = data.map((item: any) => {
        return resourceNodeSchemaResponseTransformer(item);
    });
    return data;
};

const resourceNodeSchemaResponseTransformer = (data: any) => {
    data.children = data.children.map((item: any) => {
        return resourceNodeSchemaResponseTransformer(item);
    });
    return data;
};

export const postAdminResourceUserResourceTreeResponseTransformer = async (data: any): Promise<PostAdminResourceUserResourceTreeResponse> => {
    data = data.map((item: any) => {
        return resourceNodeSchemaResponseTransformer(item);
    });
    return data;
};

export const postAdminResourceRoleResourceTreeResponseTransformer = async (data: any): Promise<PostAdminResourceRoleResourceTreeResponse> => {
    data = data.map((item: any) => {
        return resourceNodeSchemaResponseTransformer(item);
    });
    return data;
};

export const postAdminResourceRoleGrantResourceTreeResponseTransformer = async (data: any): Promise<PostAdminResourceRoleGrantResourceTreeResponse> => {
    data = data.map((item: any) => {
        return grantResourceNodeSchemaResponseTransformer(item);
    });
    return data;
};

const grantResourceNodeSchemaResponseTransformer = (data: any) => {
    data.children = data.children.map((item: any) => {
        return grantResourceNodeSchemaResponseTransformer(item);
    });
    return data;
};

export const postAdminUserSignInResponseTransformer = async (data: any): Promise<PostAdminUserSignInResponse> => {
    data.resourceTree = data.resourceTree.map((item: any) => {
        return resourceNodeSchemaResponseTransformer(item);
    });
    return data;
};

export const postAdminCategoryTreeResponseTransformer = async (data: any): Promise<PostAdminCategoryTreeResponse> => {
    data = data.map((item: any) => {
        return categoryNodeSchemaResponseTransformer(item);
    });
    return data;
};

const categoryNodeSchemaResponseTransformer = (data: any) => {
    data.children = data.children.map((item: any) => {
        return categoryNodeSchemaResponseTransformer(item);
    });
    return data;
};

export const postAdminCategoryEnabledTreeResponseTransformer = async (data: any): Promise<PostAdminCategoryEnabledTreeResponse> => {
    data = data.map((item: any) => {
        return categoryNodeSchemaResponseTransformer(item);
    });
    return data;
};
