export const countries = [
  // 东亚 East Asia
  { code: 'CN', enUs: 'China', zhCn: '中国', region: 'Asia' },
  { code: 'JP', enUs: 'Japan', zhCn: '日本', region: 'Asia' },
  { code: 'KR', enUs: 'South Korea', zhCn: '韩国', region: 'Asia' },
  { code: 'KP', enUs: 'North Korea', zhCn: '朝鲜', region: 'Asia' },
  { code: 'MN', enUs: 'Mongolia', zhCn: '蒙古', region: 'Asia' },
  { code: 'HK', enUs: 'Hong Kong', zhCn: '香港', region: 'Asia' },
  { code: 'MO', enUs: 'Macao', zhCn: '澳门', region: 'Asia' },
  { code: 'TW', enUs: 'Taiwan', zhCn: '台湾', region: 'Asia' },

  // 东南亚 Southeast Asia
  { code: 'TH', enUs: 'Thailand', zhCn: '泰国', region: 'Asia' },
  { code: 'VN', enUs: 'Vietnam', zhCn: '越南', region: 'Asia' },
  { code: 'SG', enUs: 'Singapore', zhCn: '新加坡', region: 'Asia' },
  { code: 'MY', enUs: 'Malaysia', zhCn: '马来西亚', region: 'Asia' },
  { code: 'ID', enUs: 'Indonesia', zhCn: '印度尼西亚', region: 'Asia' },
  { code: 'PH', enUs: 'Philippines', zhCn: '菲律宾', region: 'Asia' },
  { code: 'MM', enUs: 'Myanmar', zhCn: '缅甸', region: 'Asia' },
  { code: 'KH', enUs: 'Cambodia', zhCn: '柬埔寨', region: 'Asia' },
  { code: 'LA', enUs: 'Laos', zhCn: '老挝', region: 'Asia' },
  { code: 'BN', enUs: 'Brunei', zhCn: '文莱', region: 'Asia' },
  { code: 'TL', enUs: 'Timor-Leste', zhCn: '东帝汶', region: 'Asia' },

  // 南亚 South Asia
  { code: 'IN', enUs: 'India', zhCn: '印度', region: 'Asia' },
  { code: 'PK', enUs: 'Pakistan', zhCn: '巴基斯坦', region: 'Asia' },
  { code: 'BD', enUs: 'Bangladesh', zhCn: '孟加拉国', region: 'Asia' },
  { code: 'LK', enUs: 'Sri Lanka', zhCn: '斯里兰卡', region: 'Asia' },
  { code: 'NP', enUs: 'Nepal', zhCn: '尼泊尔', region: 'Asia' },
  { code: 'BT', enUs: 'Bhutan', zhCn: '不丹', region: 'Asia' },
  { code: 'MV', enUs: 'Maldives', zhCn: '马尔代夫', region: 'Asia' },
  { code: 'AF', enUs: 'Afghanistan', zhCn: '阿富汗', region: 'Asia' },

  // 中亚 Central Asia
  { code: 'KZ', enUs: 'Kazakhstan', zhCn: '哈萨克斯坦', region: 'Asia' },
  { code: 'UZ', enUs: 'Uzbekistan', zhCn: '乌兹别克斯坦', region: 'Asia' },
  { code: 'TM', enUs: 'Turkmenistan', zhCn: '土库曼斯坦', region: 'Asia' },
  { code: 'KG', enUs: 'Kyrgyzstan', zhCn: '吉尔吉斯斯坦', region: 'Asia' },
  { code: 'TJ', enUs: 'Tajikistan', zhCn: '塔吉克斯坦', region: 'Asia' },

  // 西亚/中东 West Asia/Middle East
  { code: 'TR', enUs: 'Turkey', zhCn: '土耳其', region: 'Asia' },
  { code: 'SA', enUs: 'Saudi Arabia', zhCn: '沙特阿拉伯', region: 'Asia' },
  { code: 'AE', enUs: 'United Arab Emirates', zhCn: '阿联酋', region: 'Asia' },
  { code: 'IL', enUs: 'Israel', zhCn: '以色列', region: 'Asia' },
  { code: 'IR', enUs: 'Iran', zhCn: '伊朗', region: 'Asia' },
  { code: 'IQ', enUs: 'Iraq', zhCn: '伊拉克', region: 'Asia' },
  { code: 'SY', enUs: 'Syria', zhCn: '叙利亚', region: 'Asia' },
  { code: 'JO', enUs: 'Jordan', zhCn: '约旦', region: 'Asia' },
  { code: 'LB', enUs: 'Lebanon', zhCn: '黎巴嫩', region: 'Asia' },
  { code: 'PS', enUs: 'Palestine', zhCn: '巴勒斯坦', region: 'Asia' },
  { code: 'YE', enUs: 'Yemen', zhCn: '也门', region: 'Asia' },
  { code: 'OM', enUs: 'Oman', zhCn: '阿曼', region: 'Asia' },
  { code: 'KW', enUs: 'Kuwait', zhCn: '科威特', region: 'Asia' },
  { code: 'QA', enUs: 'Qatar', zhCn: '卡塔尔', region: 'Asia' },
  { code: 'BH', enUs: 'Bahrain', zhCn: '巴林', region: 'Asia' },
  { code: 'AM', enUs: 'Armenia', zhCn: '亚美尼亚', region: 'Asia' },
  { code: 'AZ', enUs: 'Azerbaijan', zhCn: '阿塞拜疆', region: 'Asia' },
  { code: 'GE', enUs: 'Georgia', zhCn: '格鲁吉亚', region: 'Asia' },
  { code: 'CY', enUs: 'Cyprus', zhCn: '塞浦路斯', region: 'Asia' },

  // 西欧 Western Europe
  { code: 'GB', enUs: 'United Kingdom', zhCn: '英国', region: 'Europe' },
  { code: 'FR', enUs: 'France', zhCn: '法国', region: 'Europe' },
  { code: 'DE', enUs: 'Germany', zhCn: '德国', region: 'Europe' },
  { code: 'NL', enUs: 'Netherlands', zhCn: '荷兰', region: 'Europe' },
  { code: 'BE', enUs: 'Belgium', zhCn: '比利时', region: 'Europe' },
  { code: 'LU', enUs: 'Luxembourg', zhCn: '卢森堡', region: 'Europe' },
  { code: 'CH', enUs: 'Switzerland', zhCn: '瑞士', region: 'Europe' },
  { code: 'AT', enUs: 'Austria', zhCn: '奥地利', region: 'Europe' },
  { code: 'IE', enUs: 'Ireland', zhCn: '爱尔兰', region: 'Europe' },
  { code: 'MC', enUs: 'Monaco', zhCn: '摩纳哥', region: 'Europe' },
  { code: 'LI', enUs: 'Liechtenstein', zhCn: '列支敦士登', region: 'Europe' },

  // 南欧 Southern Europe
  { code: 'IT', enUs: 'Italy', zhCn: '意大利', region: 'Europe' },
  { code: 'ES', enUs: 'Spain', zhCn: '西班牙', region: 'Europe' },
  { code: 'PT', enUs: 'Portugal', zhCn: '葡萄牙', region: 'Europe' },
  { code: 'GR', enUs: 'Greece', zhCn: '希腊', region: 'Europe' },
  { code: 'MT', enUs: 'Malta', zhCn: '马耳他', region: 'Europe' },
  { code: 'AD', enUs: 'Andorra', zhCn: '安道尔', region: 'Europe' },
  { code: 'SM', enUs: 'San Marino', zhCn: '圣马力诺', region: 'Europe' },
  { code: 'VA', enUs: 'Vatican City', zhCn: '梵蒂冈', region: 'Europe' },
  { code: 'SI', enUs: 'Slovenia', zhCn: '斯洛文尼亚', region: 'Europe' },
  { code: 'HR', enUs: 'Croatia', zhCn: '克罗地亚', region: 'Europe' },
  { code: 'BA', enUs: 'Bosnia and Herzegovina', zhCn: '波黑', region: 'Europe' },
  { code: 'ME', enUs: 'Montenegro', zhCn: '黑山', region: 'Europe' },
  { code: 'RS', enUs: 'Serbia', zhCn: '塞尔维亚', region: 'Europe' },
  { code: 'MK', enUs: 'North Macedonia', zhCn: '北马其顿', region: 'Europe' },
  { code: 'AL', enUs: 'Albania', zhCn: '阿尔巴尼亚', region: 'Europe' },
  { code: 'XK', enUs: 'Kosovo', zhCn: '科索沃', region: 'Europe' },

  // 北欧 Northern Europe
  { code: 'SE', enUs: 'Sweden', zhCn: '瑞典', region: 'Europe' },
  { code: 'NO', enUs: 'Norway', zhCn: '挪威', region: 'Europe' },
  { code: 'DK', enUs: 'Denmark', zhCn: '丹麦', region: 'Europe' },
  { code: 'FI', enUs: 'Finland', zhCn: '芬兰', region: 'Europe' },
  { code: 'IS', enUs: 'Iceland', zhCn: '冰岛', region: 'Europe' },
  { code: 'FO', enUs: 'Faroe Islands', zhCn: '法罗群岛', region: 'Europe' },
  { code: 'AX', enUs: 'Åland Islands', zhCn: '奥兰群岛', region: 'Europe' },
  { code: 'GL', enUs: 'Greenland', zhCn: '格陵兰', region: 'Europe' },

  // 东欧 Eastern Europe
  { code: 'RU', enUs: 'Russia', zhCn: '俄罗斯', region: 'Europe' },
  { code: 'PL', enUs: 'Poland', zhCn: '波兰', region: 'Europe' },
  { code: 'CZ', enUs: 'Czech Republic', zhCn: '捷克', region: 'Europe' },
  { code: 'SK', enUs: 'Slovakia', zhCn: '斯洛伐克', region: 'Europe' },
  { code: 'HU', enUs: 'Hungary', zhCn: '匈牙利', region: 'Europe' },
  { code: 'RO', enUs: 'Romania', zhCn: '罗马尼亚', region: 'Europe' },
  { code: 'BG', enUs: 'Bulgaria', zhCn: '保加利亚', region: 'Europe' },
  { code: 'UA', enUs: 'Ukraine', zhCn: '乌克兰', region: 'Europe' },
  { code: 'BY', enUs: 'Belarus', zhCn: '白俄罗斯', region: 'Europe' },
  { code: 'MD', enUs: 'Moldova', zhCn: '摩尔多瓦', region: 'Europe' },
  { code: 'EE', enUs: 'Estonia', zhCn: '爱沙尼亚', region: 'Europe' },
  { code: 'LV', enUs: 'Latvia', zhCn: '拉脱维亚', region: 'Europe' },
  { code: 'LT', enUs: 'Lithuania', zhCn: '立陶宛', region: 'Europe' },

  // 北美洲 North America
  { code: 'US', enUs: 'United States', zhCn: '美国', region: 'North America' },
  { code: 'CA', enUs: 'Canada', zhCn: '加拿大', region: 'North America' },
  { code: 'MX', enUs: 'Mexico', zhCn: '墨西哥', region: 'North America' },
  { code: 'GT', enUs: 'Guatemala', zhCn: '危地马拉', region: 'North America' },
  { code: 'BZ', enUs: 'Belize', zhCn: '伯利兹', region: 'North America' },
  { code: 'SV', enUs: 'El Salvador', zhCn: '萨尔瓦多', region: 'North America' },
  { code: 'HN', enUs: 'Honduras', zhCn: '洪都拉斯', region: 'North America' },
  { code: 'NI', enUs: 'Nicaragua', zhCn: '尼加拉瓜', region: 'North America' },
  { code: 'CR', enUs: 'Costa Rica', zhCn: '哥斯达黎加', region: 'North America' },
  { code: 'PA', enUs: 'Panama', zhCn: '巴拿马', region: 'North America' },

  // 加勒比地区 Caribbean
  { code: 'CU', enUs: 'Cuba', zhCn: '古巴', region: 'North America' },
  { code: 'JM', enUs: 'Jamaica', zhCn: '牙买加', region: 'North America' },
  { code: 'HT', enUs: 'Haiti', zhCn: '海地', region: 'North America' },
  { code: 'DO', enUs: 'Dominican Republic', zhCn: '多米尼加', region: 'North America' },
  { code: 'PR', enUs: 'Puerto Rico', zhCn: '波多黎各', region: 'North America' },
  { code: 'TT', enUs: 'Trinidad and Tobago', zhCn: '特立尼达和多巴哥', region: 'North America' },
  { code: 'BB', enUs: 'Barbados', zhCn: '巴巴多斯', region: 'North America' },
  { code: 'BS', enUs: 'Bahamas', zhCn: '巴哈马', region: 'North America' },
  { code: 'LC', enUs: 'Saint Lucia', zhCn: '圣卢西亚', region: 'North America' },
  { code: 'GD', enUs: 'Grenada', zhCn: '格林纳达', region: 'North America' },
  {
    code: 'VC',
    enUs: 'Saint Vincent and the Grenadines',
    zhCn: '圣文森特和格林纳丁斯',
    region: 'North America'
  },
  { code: 'AG', enUs: 'Antigua and Barbuda', zhCn: '安提瓜和巴布达', region: 'North America' },
  { code: 'DM', enUs: 'Dominica', zhCn: '多米尼克', region: 'North America' },
  { code: 'KN', enUs: 'Saint Kitts and Nevis', zhCn: '圣基茨和尼维斯', region: 'North America' },
  { code: 'BM', enUs: 'Bermuda', zhCn: '百慕大', region: 'North America' },
  { code: 'KY', enUs: 'Cayman Islands', zhCn: '开曼群岛', region: 'North America' },
  { code: 'VG', enUs: 'British Virgin Islands', zhCn: '英属维尔京群岛', region: 'North America' },
  { code: 'VI', enUs: 'U.S. Virgin Islands', zhCn: '美属维尔京群岛', region: 'North America' },
  {
    code: 'TC',
    enUs: 'Turks and Caicos Islands',
    zhCn: '特克斯和凯科斯群岛',
    region: 'North America'
  },
  { code: 'MS', enUs: 'Montserrat', zhCn: '蒙特塞拉特', region: 'North America' },
  { code: 'AI', enUs: 'Anguilla', zhCn: '安圭拉', region: 'North America' },
  { code: 'GP', enUs: 'Guadeloupe', zhCn: '瓜德罗普', region: 'North America' },
  { code: 'MQ', enUs: 'Martinique', zhCn: '马提尼克', region: 'North America' },
  { code: 'BL', enUs: 'Saint Barthélemy', zhCn: '圣巴泰勒米', region: 'North America' },
  { code: 'MF', enUs: 'Saint Martin', zhCn: '法属圣马丁', region: 'North America' },
  { code: 'SX', enUs: 'Sint Maarten', zhCn: '荷属圣马丁', region: 'North America' },
  { code: 'CW', enUs: 'Curaçao', zhCn: '库拉索', region: 'North America' },
  { code: 'AW', enUs: 'Aruba', zhCn: '阿鲁巴', region: 'North America' },
  {
    code: 'PM',
    enUs: 'Saint Pierre and Miquelon',
    zhCn: '圣皮埃尔和密克隆',
    region: 'North America'
  },

  // 南美洲 South America
  { code: 'BR', enUs: 'Brazil', zhCn: '巴西', region: 'South America' },
  { code: 'AR', enUs: 'Argentina', zhCn: '阿根廷', region: 'South America' },
  { code: 'CL', enUs: 'Chile', zhCn: '智利', region: 'South America' },
  { code: 'CO', enUs: 'Colombia', zhCn: '哥伦比亚', region: 'South America' },
  { code: 'PE', enUs: 'Peru', zhCn: '秘鲁', region: 'South America' },
  { code: 'VE', enUs: 'Venezuela', zhCn: '委内瑞拉', region: 'South America' },
  { code: 'EC', enUs: 'Ecuador', zhCn: '厄瓜多尔', region: 'South America' },
  { code: 'BO', enUs: 'Bolivia', zhCn: '玻利维亚', region: 'South America' },
  { code: 'PY', enUs: 'Paraguay', zhCn: '巴拉圭', region: 'South America' },
  { code: 'UY', enUs: 'Uruguay', zhCn: '乌拉圭', region: 'South America' },
  { code: 'GY', enUs: 'Guyana', zhCn: '圭亚那', region: 'South America' },
  { code: 'SR', enUs: 'Suriname', zhCn: '苏里南', region: 'South America' },
  { code: 'GF', enUs: 'French Guiana', zhCn: '法属圭亚那', region: 'South America' },
  { code: 'FK', enUs: 'Falkland Islands', zhCn: '福克兰群岛', region: 'South America' },
  {
    code: 'GS',
    enUs: 'South Georgia and the South Sandwich Islands',
    zhCn: '南乔治亚和南桑威奇群岛',
    region: 'South America'
  },

  // 北非 North Africa
  { code: 'EG', enUs: 'Egypt', zhCn: '埃及', region: 'Africa' },
  { code: 'LY', enUs: 'Libya', zhCn: '利比亚', region: 'Africa' },
  { code: 'TN', enUs: 'Tunisia', zhCn: '突尼斯', region: 'Africa' },
  { code: 'DZ', enUs: 'Algeria', zhCn: '阿尔及利亚', region: 'Africa' },
  { code: 'MA', enUs: 'Morocco', zhCn: '摩洛哥', region: 'Africa' },
  { code: 'EH', enUs: 'Western Sahara', zhCn: '西撒哈拉', region: 'Africa' },
  { code: 'SD', enUs: 'Sudan', zhCn: '苏丹', region: 'Africa' },
  { code: 'SS', enUs: 'South Sudan', zhCn: '南苏丹', region: 'Africa' },

  // 西非 West Africa
  { code: 'NG', enUs: 'Nigeria', zhCn: '尼日利亚', region: 'Africa' },
  { code: 'GH', enUs: 'Ghana', zhCn: '加纳', region: 'Africa' },
  { code: 'CI', enUs: 'Ivory Coast', zhCn: '科特迪瓦', region: 'Africa' },
  { code: 'SN', enUs: 'Senegal', zhCn: '塞内加尔', region: 'Africa' },
  { code: 'ML', enUs: 'Mali', zhCn: '马里', region: 'Africa' },
  { code: 'BF', enUs: 'Burkina Faso', zhCn: '布基纳法索', region: 'Africa' },
  { code: 'NE', enUs: 'Niger', zhCn: '尼日尔', region: 'Africa' },
  { code: 'GN', enUs: 'Guinea', zhCn: '几内亚', region: 'Africa' },
  { code: 'SL', enUs: 'Sierra Leone', zhCn: '塞拉利昂', region: 'Africa' },
  { code: 'LR', enUs: 'Liberia', zhCn: '利比里亚', region: 'Africa' },
  { code: 'TG', enUs: 'Togo', zhCn: '多哥', region: 'Africa' },
  { code: 'BJ', enUs: 'Benin', zhCn: '贝宁', region: 'Africa' },
  { code: 'MR', enUs: 'Mauritania', zhCn: '毛里塔尼亚', region: 'Africa' },
  { code: 'GM', enUs: 'Gambia', zhCn: '冈比亚', region: 'Africa' },
  { code: 'GW', enUs: 'Guinea-Bissau', zhCn: '几内亚比绍', region: 'Africa' },
  { code: 'CV', enUs: 'Cape Verde', zhCn: '佛得角', region: 'Africa' },

  // 中非 Central Africa
  { code: 'CD', enUs: 'Democratic Republic of the Congo', zhCn: '刚果（金）', region: 'Africa' },
  { code: 'CG', enUs: 'Republic of the Congo', zhCn: '刚果（布）', region: 'Africa' },
  { code: 'CM', enUs: 'Cameroon', zhCn: '喀麦隆', region: 'Africa' },
  { code: 'CF', enUs: 'Central African Republic', zhCn: '中非', region: 'Africa' },
  { code: 'TD', enUs: 'Chad', zhCn: '乍得', region: 'Africa' },
  { code: 'GA', enUs: 'Gabon', zhCn: '加蓬', region: 'Africa' },
  { code: 'GQ', enUs: 'Equatorial Guinea', zhCn: '赤道几内亚', region: 'Africa' },
  { code: 'ST', enUs: 'Sao Tome and Principe', zhCn: '圣多美和普林西比', region: 'Africa' },
  { code: 'AO', enUs: 'Angola', zhCn: '安哥拉', region: 'Africa' },

  // 东非 East Africa
  { code: 'KE', enUs: 'Kenya', zhCn: '肯尼亚', region: 'Africa' },
  { code: 'ET', enUs: 'Ethiopia', zhCn: '埃塞俄比亚', region: 'Africa' },
  { code: 'TZ', enUs: 'Tanzania', zhCn: '坦桑尼亚', region: 'Africa' },
  { code: 'UG', enUs: 'Uganda', zhCn: '乌干达', region: 'Africa' },
  { code: 'SO', enUs: 'Somalia', zhCn: '索马里', region: 'Africa' },
  { code: 'DJ', enUs: 'Djibouti', zhCn: '吉布提', region: 'Africa' },
  { code: 'ER', enUs: 'Eritrea', zhCn: '厄立特里亚', region: 'Africa' },
  { code: 'RW', enUs: 'Rwanda', zhCn: '卢旺达', region: 'Africa' },
  { code: 'BI', enUs: 'Burundi', zhCn: '布隆迪', region: 'Africa' },
  { code: 'SC', enUs: 'Seychelles', zhCn: '塞舌尔', region: 'Africa' },
  { code: 'MU', enUs: 'Mauritius', zhCn: '毛里求斯', region: 'Africa' },
  { code: 'KM', enUs: 'Comoros', zhCn: '科摩罗', region: 'Africa' },
  { code: 'MG', enUs: 'Madagascar', zhCn: '马达加斯加', region: 'Africa' },
  { code: 'RE', enUs: 'Réunion', zhCn: '留尼汪', region: 'Africa' },
  { code: 'YT', enUs: 'Mayotte', zhCn: '马约特', region: 'Africa' },

  // 南非 Southern Africa
  { code: 'ZA', enUs: 'South Africa', zhCn: '南非', region: 'Africa' },
  { code: 'ZW', enUs: 'Zimbabwe', zhCn: '津巴布韦', region: 'Africa' },
  { code: 'ZM', enUs: 'Zambia', zhCn: '赞比亚', region: 'Africa' },
  { code: 'MW', enUs: 'Malawi', zhCn: '马拉维', region: 'Africa' },
  { code: 'MZ', enUs: 'Mozambique', zhCn: '莫桑比克', region: 'Africa' },
  { code: 'BW', enUs: 'Botswana', zhCn: '博茨瓦纳', region: 'Africa' },
  { code: 'NA', enUs: 'Namibia', zhCn: '纳米比亚', region: 'Africa' },
  { code: 'LS', enUs: 'Lesotho', zhCn: '莱索托', region: 'Africa' },
  { code: 'SZ', enUs: 'Eswatini', zhCn: '斯威士兰', region: 'Africa' },
  { code: 'SH', enUs: 'Saint Helena', zhCn: '圣赫勒拿', region: 'Africa' },

  // 澳大利亚和新西兰 Australia and New Zealand
  { code: 'AU', enUs: 'Australia', zhCn: '澳大利亚', region: 'Oceania' },
  { code: 'NZ', enUs: 'New Zealand', zhCn: '新西兰', region: 'Oceania' },
  { code: 'NF', enUs: 'Norfolk Island', zhCn: '诺福克岛', region: 'Oceania' },
  { code: 'CX', enUs: 'Christmas Island', zhCn: '圣诞岛', region: 'Oceania' },
  { code: 'CC', enUs: 'Cocos (Keeling) Islands', zhCn: '科科斯群岛', region: 'Oceania' },
  {
    code: 'HM',
    enUs: 'Heard Island and McDonald Islands',
    zhCn: '赫德岛和麦克唐纳群岛',
    region: 'Oceania'
  },

  // 美拉尼西亚 Melanesia
  { code: 'PG', enUs: 'Papua New Guinea', zhCn: '巴布亚新几内亚', region: 'Oceania' },
  { code: 'FJ', enUs: 'Fiji', zhCn: '斐济', region: 'Oceania' },
  { code: 'SB', enUs: 'Solomon Islands', zhCn: '所罗门群岛', region: 'Oceania' },
  { code: 'VU', enUs: 'Vanuatu', zhCn: '瓦努阿图', region: 'Oceania' },
  { code: 'NC', enUs: 'New Caledonia', zhCn: '新喀里多尼亚', region: 'Oceania' },

  // 密克罗尼西亚 Micronesia
  { code: 'GU', enUs: 'Guam', zhCn: '关岛', region: 'Oceania' },
  { code: 'MP', enUs: 'Northern Mariana Islands', zhCn: '北马里亚纳群岛', region: 'Oceania' },
  { code: 'FM', enUs: 'Micronesia', zhCn: '密克罗尼西亚', region: 'Oceania' },
  { code: 'PW', enUs: 'Palau', zhCn: '帕劳', region: 'Oceania' },
  { code: 'MH', enUs: 'Marshall Islands', zhCn: '马绍尔群岛', region: 'Oceania' },
  { code: 'NR', enUs: 'Nauru', zhCn: '瑙鲁', region: 'Oceania' },
  { code: 'KI', enUs: 'Kiribati', zhCn: '基里巴斯', region: 'Oceania' },

  // 波利尼西亚 Polynesia
  { code: 'WS', enUs: 'Samoa', zhCn: '萨摩亚', region: 'Oceania' },
  { code: 'TO', enUs: 'Tonga', zhCn: '汤加', region: 'Oceania' },
  { code: 'TV', enUs: 'Tuvalu', zhCn: '图瓦卢', region: 'Oceania' },
  { code: 'PF', enUs: 'French Polynesia', zhCn: '法属波利尼西亚', region: 'Oceania' },
  { code: 'CK', enUs: 'Cook Islands', zhCn: '库克群岛', region: 'Oceania' },
  { code: 'NU', enUs: 'Niue', zhCn: '纽埃', region: 'Oceania' },
  { code: 'TK', enUs: 'Tokelau', zhCn: '托克劳', region: 'Oceania' },
  { code: 'WF', enUs: 'Wallis and Futuna', zhCn: '瓦利斯和富图纳', region: 'Oceania' },
  { code: 'PN', enUs: 'Pitcairn Islands', zhCn: '皮特凯恩群岛', region: 'Oceania' },
  { code: 'AS', enUs: 'American Samoa', zhCn: '美属萨摩亚', region: 'Oceania' },
  { code: 'UM', enUs: 'U.S. Minor Outlying Islands', zhCn: '美国本土外小岛屿', region: 'Oceania' },

  // 其他地区 Other Territories
  { code: 'AQ', enUs: 'Antarctica', zhCn: '南极洲', region: 'Antarctica' },
  { code: 'BV', enUs: 'Bouvet Island', zhCn: '布韦岛', region: 'Antarctica' },
  { code: 'TF', enUs: 'French Southern Territories', zhCn: '法属南部领地', region: 'Antarctica' },
  { code: 'GI', enUs: 'Gibraltar', zhCn: '直布罗陀', region: 'Europe' },
  { code: 'IO', enUs: 'British Indian Ocean Territory', zhCn: '英属印度洋领地', region: 'Asia' }
]
