networks:
  youde-network:
    external: true
volumes:
  db-data-dev:
    external: true
  db-log-dev:
    external: true
services:
  admin:
    image: ghcr.io/javionlog/youde-admin-dev:latest
    container_name: admin-dev
    volumes:
      - /apps/youde-dev/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - youde-network
    depends_on:
      - api
  portal:
    image: ghcr.io/javionlog/youde-portal-dev:latest
    container_name: portal-dev
    networks:
      - youde-network
    depends_on:
      - api
    env_file:
      - 1panel.env
  api:
    image: ghcr.io/javionlog/youde-api-dev:latest
    container_name: api-dev
    networks:
      - youde-network
    depends_on:
      - db
    env_file:
      - 1panel.env
  db:
    image: postgres:alpine
    container_name: db-dev
    volumes:
      - db-data-dev:/var/lib/postgresql/data
      - db-log-dev:/var/log/postgresql
    ports:
      - 5433:5432
    networks:
      - youde-network
    env_file:
      - 1panel.env
