networks:
  youde-network:
    external: true
services:
  gateway:
    image: nginx:alpine
    container_name: gateway
    ports:
      - 80:80
    volumes:
      - /apps/gateway/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - youde-network
