// This file is auto-generated by @hey-api/openapi-ts

export const ResourceNodeSchema = {
    '$schema': 'https://json-schema.org/draft/2020-12/schema',
    '$id': '#/components/schemas/ResourceNode',
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        createdAt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        updatedAt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        createdBy: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        updatedBy: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        name: {
            type: 'string',
            maxLength: 64
        },
        enabled: {
            type: 'boolean'
        },
        remark: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128
                },
                {
                    type: 'null'
                }
            ]
        },
        sort: {
            type: 'integer',
            minimum: -2147483648,
            maximum: 2147483647
        },
        parentId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        type: {
            type: 'string',
            enum: ['Menu', 'Page', 'Element']
        },
        path: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 256
                },
                {
                    type: 'null'
                }
            ]
        },
        activePath: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 256
                },
                {
                    type: 'null'
                }
            ]
        },
        component: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 256
                },
                {
                    type: 'null'
                }
            ]
        },
        icon: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 256
                },
                {
                    type: 'null'
                }
            ]
        },
        isLink: {
            type: 'boolean'
        },
        isCache: {
            type: 'boolean'
        },
        isAffix: {
            type: 'boolean'
        },
        isShow: {
            type: 'boolean'
        },
        locales: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    id: {
                        type: 'string'
                    },
                    createdAt: {
                        anyOf: [
                            {
                                type: 'string'
                            },
                            {
                                type: 'null'
                            }
                        ]
                    },
                    updatedAt: {
                        anyOf: [
                            {
                                type: 'string'
                            },
                            {
                                type: 'null'
                            }
                        ]
                    },
                    createdBy: {
                        anyOf: [
                            {
                                type: 'string'
                            },
                            {
                                type: 'null'
                            }
                        ]
                    },
                    updatedBy: {
                        anyOf: [
                            {
                                type: 'string'
                            },
                            {
                                type: 'null'
                            }
                        ]
                    },
                    resourceId: {
                        type: 'string'
                    },
                    field: {
                        type: 'string',
                        enum: ['name']
                    },
                    enUs: {
                        type: 'string',
                        maxLength: 64
                    },
                    zhCn: {
                        type: 'string',
                        maxLength: 64
                    }
                },
                required: ['id', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy', 'resourceId', 'field', 'enUs', 'zhCn'],
                additionalProperties: false
            }
        },
        children: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ResourceNode'
            }
        }
    },
    required: ['id', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy', 'name', 'enabled', 'remark', 'sort', 'parentId', 'type', 'path', 'activePath', 'component', 'icon', 'isLink', 'isCache', 'isAffix', 'isShow', 'locales', 'children'],
    additionalProperties: false,
    id: 'ResourceNode'
} as const;

export const GrantResourceNodeSchema = {
    '$schema': 'https://json-schema.org/draft/2020-12/schema',
    '$id': '#/components/schemas/GrantResourceNode',
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        createdAt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        updatedAt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        createdBy: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        updatedBy: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        name: {
            type: 'string',
            maxLength: 64
        },
        enabled: {
            type: 'boolean'
        },
        remark: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128
                },
                {
                    type: 'null'
                }
            ]
        },
        sort: {
            type: 'integer',
            minimum: -2147483648,
            maximum: 2147483647
        },
        parentId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        type: {
            type: 'string',
            enum: ['Menu', 'Page', 'Element']
        },
        path: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 256
                },
                {
                    type: 'null'
                }
            ]
        },
        activePath: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 256
                },
                {
                    type: 'null'
                }
            ]
        },
        component: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 256
                },
                {
                    type: 'null'
                }
            ]
        },
        icon: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 256
                },
                {
                    type: 'null'
                }
            ]
        },
        isLink: {
            type: 'boolean'
        },
        isCache: {
            type: 'boolean'
        },
        isAffix: {
            type: 'boolean'
        },
        isShow: {
            type: 'boolean'
        },
        locales: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    id: {
                        type: 'string'
                    },
                    createdAt: {
                        anyOf: [
                            {
                                type: 'string'
                            },
                            {
                                type: 'null'
                            }
                        ]
                    },
                    updatedAt: {
                        anyOf: [
                            {
                                type: 'string'
                            },
                            {
                                type: 'null'
                            }
                        ]
                    },
                    createdBy: {
                        anyOf: [
                            {
                                type: 'string'
                            },
                            {
                                type: 'null'
                            }
                        ]
                    },
                    updatedBy: {
                        anyOf: [
                            {
                                type: 'string'
                            },
                            {
                                type: 'null'
                            }
                        ]
                    },
                    resourceId: {
                        type: 'string'
                    },
                    field: {
                        type: 'string',
                        enum: ['name']
                    },
                    enUs: {
                        type: 'string',
                        maxLength: 64
                    },
                    zhCn: {
                        type: 'string',
                        maxLength: 64
                    }
                },
                required: ['id', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy', 'resourceId', 'field', 'enUs', 'zhCn'],
                additionalProperties: false
            }
        },
        grant: {
            type: 'boolean'
        },
        children: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/GrantResourceNode'
            }
        }
    },
    required: ['id', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy', 'name', 'enabled', 'remark', 'sort', 'parentId', 'type', 'path', 'activePath', 'component', 'icon', 'isLink', 'isCache', 'isAffix', 'isShow', 'locales', 'grant', 'children'],
    additionalProperties: false,
    id: 'GrantResourceNode'
} as const;
