// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import { postPortalTreasureCategoryTreeResponseTransformer } from './transformers.gen';
import type { GetPortalTreasureCategoryLocaleData, GetPortalTreasureCategoryLocaleResponses, GetPortalTreasureData, GetPortalTreasureResponses, PostPortalCountryListData, PostPortalCountryListResponses, PostPortalTreasureCategoryTreeData, PostPortalTreasureCategoryTreeResponses, PostPortalTreasureListData, PostPortalTreasureListResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List countries
 */
export const postPortalCountryList = <ThrowOnError extends boolean = false>(options: Options<PostPortalCountryListData, ThrowOnError>) => {
    return (options.client ?? client).post<PostPortalCountryListResponses, unknown, ThrowOnError>({
        url: '/portal/country/list',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get treasure
 */
export const getPortalTreasure = <ThrowOnError extends boolean = false>(options?: Options<GetPortalTreasureData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetPortalTreasureResponses, unknown, ThrowOnError>({
        url: '/portal/treasure',
        ...options
    });
};

/**
 * List treasures
 */
export const postPortalTreasureList = <ThrowOnError extends boolean = false>(options: Options<PostPortalTreasureListData, ThrowOnError>) => {
    return (options.client ?? client).post<PostPortalTreasureListResponses, unknown, ThrowOnError>({
        url: '/portal/treasure/list',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List treasure category tree
 */
export const postPortalTreasureCategoryTree = <ThrowOnError extends boolean = false>(options: Options<PostPortalTreasureCategoryTreeData, ThrowOnError>) => {
    return (options.client ?? client).post<PostPortalTreasureCategoryTreeResponses, unknown, ThrowOnError>({
        responseTransformer: postPortalTreasureCategoryTreeResponseTransformer,
        url: '/portal/treasure-category/tree',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get treasure category locale
 */
export const getPortalTreasureCategoryLocale = <ThrowOnError extends boolean = false>(options?: Options<GetPortalTreasureCategoryLocaleData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetPortalTreasureCategoryLocaleResponses, unknown, ThrowOnError>({
        url: '/portal/treasure-category-locale',
        ...options
    });
};
