// This file is auto-generated by @hey-api/openapi-ts

import type { PostPortalTreasureCategoryTreeResponse } from './types.gen';

export const postPortalTreasureCategoryTreeResponseTransformer = async (data: any): Promise<PostPortalTreasureCategoryTreeResponse> => {
    data = data.map((item: any) => {
        return treasureCategoryNodeSchemaResponseTransformer(item);
    });
    return data;
};

const treasureCategoryNodeSchemaResponseTransformer = (data: any) => {
    data.children = data.children.map((item: any) => {
        return treasureCategoryNodeSchemaResponseTransformer(item);
    });
    return data;
};
