// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type TreasureCategoryNode = {
    id: string;
    createdAt: string | null;
    updatedAt: string | null;
    createdBy: string | null;
    updatedBy: string | null;
    parentId: string | null;
    name: string;
    enabled: boolean;
    sort: number;
    locales: Array<{
        id: string;
        createdAt: string | null;
        updatedAt: string | null;
        createdBy: string | null;
        updatedBy: string | null;
        categoryId: string;
        field: 'name';
        enUs: string;
        zhCn: string;
    }>;
    children: Array<TreasureCategoryNode>;
};

export type PostPortalCountryListData = {
    body: {
        page?: number;
        pageSize?: number;
        codes?: Array<string> | null;
        regions?: Array<string> | null;
        enUs?: Array<string> | null;
        zhCn?: Array<string> | null;
        sortBy?: {
            field?: 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy' | 'code' | 'region' | 'enUs' | 'zhCn';
            direction?: 'asc' | 'desc';
        } | null;
    };
    path?: never;
    query?: never;
    url: '/portal/country/list';
};

export type PostPortalCountryListResponses = {
    /**
     * Response for status 200
     */
    200: {
        records: Array<{
            id: string;
            createdAt: string | null;
            updatedAt: string | null;
            createdBy: string | null;
            updatedBy: string | null;
            code: string;
            region: string;
            enUs: string;
            zhCn: string;
        }>;
        total: number;
    };
};

export type PostPortalCountryListResponse = PostPortalCountryListResponses[keyof PostPortalCountryListResponses];

export type GetPortalTreasureData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/portal/treasure';
};

export type GetPortalTreasureResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        createdAt: string | null;
        updatedAt: string | null;
        createdBy: string | null;
        updatedBy: string | null;
        categoryId: string;
        userId: string;
        title: string;
        description: string;
        fee: 'Free' | 'PartlyFree' | 'Paid';
        countryCode: string;
        cover: string | null;
        content: string;
        url: string;
        status: 'Draft' | 'Pending' | 'Passed';
    };
};

export type GetPortalTreasureResponse = GetPortalTreasureResponses[keyof GetPortalTreasureResponses];

export type PostPortalTreasureListData = {
    body: {
        page?: number;
        pageSize?: number;
        id?: string | null;
        title?: string | null;
        createdBy?: string | null;
        fees?: Array<'Free' | 'PartlyFree' | 'Paid'> | null;
        countryCodes?: Array<string> | null;
        categoryIds?: Array<string> | null;
        status?: Array<'Draft' | 'Pending' | 'Passed'> | null;
        sortBy?: {
            field?: 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy' | 'categoryId' | 'userId' | 'title' | 'description' | 'fee' | 'countryCode' | 'cover' | 'content' | 'url' | 'status';
            direction?: 'asc' | 'desc';
        } | null;
    };
    path?: never;
    query?: never;
    url: '/portal/treasure/list';
};

export type PostPortalTreasureListResponses = {
    /**
     * Response for status 200
     */
    200: {
        records: Array<{
            id: string;
            createdAt: string | null;
            updatedAt: string | null;
            createdBy: string | null;
            updatedBy: string | null;
            categoryId: string;
            userId: string;
            title: string;
            description: string;
            fee: 'Free' | 'PartlyFree' | 'Paid';
            countryCode: string;
            cover: string | null;
            content: string;
            url: string;
            status: 'Draft' | 'Pending' | 'Passed';
        }>;
        total: number;
    };
};

export type PostPortalTreasureListResponse = PostPortalTreasureListResponses[keyof PostPortalTreasureListResponses];

export type PostPortalTreasureCategoryTreeData = {
    body: {
        enabled?: boolean | null;
    };
    path?: never;
    query?: never;
    url: '/portal/treasure-category/tree';
};

export type PostPortalTreasureCategoryTreeResponses = {
    /**
     * Response for status 200
     */
    200: Array<TreasureCategoryNode>;
};

export type PostPortalTreasureCategoryTreeResponse = PostPortalTreasureCategoryTreeResponses[keyof PostPortalTreasureCategoryTreeResponses];

export type GetPortalTreasureCategoryLocaleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/portal/treasure-category-locale';
};

export type GetPortalTreasureCategoryLocaleResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        createdAt: string | null;
        updatedAt: string | null;
        createdBy: string | null;
        updatedBy: string | null;
        categoryId: string;
        field: 'name';
        enUs: string;
        zhCn: string;
    };
};

export type GetPortalTreasureCategoryLocaleResponse = GetPortalTreasureCategoryLocaleResponses[keyof GetPortalTreasureCategoryLocaleResponses];
