name: CI prod
on:
  push:
    branches: ['main']
    paths-ignore:
      - '.gitignore'
      - 'README.md'

  pull_request:
    branches: ['main']

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout respository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Push admin image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/admin/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}-admin-prod:latest
          build-args: |
            BUILD_MODE=prod
          # no-cache: true
          cache-from: type=gha,scope=admin-prod
          cache-to: type=gha,mode=max,scope=admin-prod

      - name: Push portal image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/portal/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}-portal-prod:latest
          build-args: |
            BUILD_MODE=prod
          # no-cache: true
          cache-from: type=gha,scope=portal-prod
          cache-to: type=gha,mode=max,scope=portal-prod

      - name: Push api image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/api/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}-api-prod:latest
          build-args: |
            BUILD_MODE=prod
          # no-cache: true
          cache-from: type=gha,scope=api-prod
          cache-to: type=gha,mode=max,scope=api-prod

      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script_path: scripts/deploy-prod.sh
