name: CI prod
on:
  push:
    branches: ['main']
    paths-ignore:
      - '.gitignore'
      - 'README.md'

  pull_request:
    branches: ['main']

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout respository
        uses: actions/checkout@v4

      - name: Setup node version
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.1'

      - name: Setup bun version
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Build apps
        run: npm run build:prod

      - name: Push admin image
        uses: docker/build-push-action@v6
        with:
          context: ./apps/admin
          push: true
          tags: ghcr.io/${{ github.repository }}-admin-prod:latest

      - name: Push api image
        uses: docker/build-push-action@v6
        with:
          context: ./apps/api
          push: true
          tags: ghcr.io/${{ github.repository }}-api-prod:latest

      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script_path: scripts/deploy-prod.sh
